/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLatihanSoalIndexRouteImport } from './routes/_authenticated/latihan-soal/index'
import { Route as AuthenticatedLatihanSoalIdRouteImport } from './routes/_authenticated/latihan-soal/$id'
import { Route as AuthenticatedLatihanSoalRiwayatIndexRouteImport } from './routes/_authenticated/latihan-soal/riwayat/index'
import { Route as AuthenticatedLatihanSoalRiwayatIdRouteImport } from './routes/_authenticated/latihan-soal/riwayat/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLatihanSoalIndexRoute =
  AuthenticatedLatihanSoalIndexRouteImport.update({
    id: '/latihan-soal/',
    path: '/latihan-soal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLatihanSoalIdRoute =
  AuthenticatedLatihanSoalIdRouteImport.update({
    id: '/latihan-soal/$id',
    path: '/latihan-soal/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLatihanSoalRiwayatIndexRoute =
  AuthenticatedLatihanSoalRiwayatIndexRouteImport.update({
    id: '/latihan-soal/riwayat/',
    path: '/latihan-soal/riwayat/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLatihanSoalRiwayatIdRoute =
  AuthenticatedLatihanSoalRiwayatIdRouteImport.update({
    id: '/latihan-soal/riwayat/$id',
    path: '/latihan-soal/riwayat/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/latihan-soal/$id': typeof AuthenticatedLatihanSoalIdRoute
  '/latihan-soal': typeof AuthenticatedLatihanSoalIndexRoute
  '/latihan-soal/riwayat/$id': typeof AuthenticatedLatihanSoalRiwayatIdRoute
  '/latihan-soal/riwayat': typeof AuthenticatedLatihanSoalRiwayatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/latihan-soal/$id': typeof AuthenticatedLatihanSoalIdRoute
  '/latihan-soal': typeof AuthenticatedLatihanSoalIndexRoute
  '/latihan-soal/riwayat/$id': typeof AuthenticatedLatihanSoalRiwayatIdRoute
  '/latihan-soal/riwayat': typeof AuthenticatedLatihanSoalRiwayatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/latihan-soal/$id': typeof AuthenticatedLatihanSoalIdRoute
  '/_authenticated/latihan-soal/': typeof AuthenticatedLatihanSoalIndexRoute
  '/_authenticated/latihan-soal/riwayat/$id': typeof AuthenticatedLatihanSoalRiwayatIdRoute
  '/_authenticated/latihan-soal/riwayat/': typeof AuthenticatedLatihanSoalRiwayatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/latihan-soal/$id'
    | '/latihan-soal'
    | '/latihan-soal/riwayat/$id'
    | '/latihan-soal/riwayat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/latihan-soal/$id'
    | '/latihan-soal'
    | '/latihan-soal/riwayat/$id'
    | '/latihan-soal/riwayat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/latihan-soal/$id'
    | '/_authenticated/latihan-soal/'
    | '/_authenticated/latihan-soal/riwayat/$id'
    | '/_authenticated/latihan-soal/riwayat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/latihan-soal/': {
      id: '/_authenticated/latihan-soal/'
      path: '/latihan-soal'
      fullPath: '/latihan-soal'
      preLoaderRoute: typeof AuthenticatedLatihanSoalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/latihan-soal/$id': {
      id: '/_authenticated/latihan-soal/$id'
      path: '/latihan-soal/$id'
      fullPath: '/latihan-soal/$id'
      preLoaderRoute: typeof AuthenticatedLatihanSoalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/latihan-soal/riwayat/': {
      id: '/_authenticated/latihan-soal/riwayat/'
      path: '/latihan-soal/riwayat'
      fullPath: '/latihan-soal/riwayat'
      preLoaderRoute: typeof AuthenticatedLatihanSoalRiwayatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/latihan-soal/riwayat/$id': {
      id: '/_authenticated/latihan-soal/riwayat/$id'
      path: '/latihan-soal/riwayat/$id'
      fullPath: '/latihan-soal/riwayat/$id'
      preLoaderRoute: typeof AuthenticatedLatihanSoalRiwayatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLatihanSoalIdRoute: typeof AuthenticatedLatihanSoalIdRoute
  AuthenticatedLatihanSoalIndexRoute: typeof AuthenticatedLatihanSoalIndexRoute
  AuthenticatedLatihanSoalRiwayatIdRoute: typeof AuthenticatedLatihanSoalRiwayatIdRoute
  AuthenticatedLatihanSoalRiwayatIndexRoute: typeof AuthenticatedLatihanSoalRiwayatIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLatihanSoalIdRoute: AuthenticatedLatihanSoalIdRoute,
  AuthenticatedLatihanSoalIndexRoute: AuthenticatedLatihanSoalIndexRoute,
  AuthenticatedLatihanSoalRiwayatIdRoute:
    AuthenticatedLatihanSoalRiwayatIdRoute,
  AuthenticatedLatihanSoalRiwayatIndexRoute:
    AuthenticatedLatihanSoalRiwayatIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
