/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedLatihanSoalIndexRouteImport } from './routes/_authenticated/latihan-soal/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AuthenticatedLatihanSoalIdRouteImport } from './routes/_authenticated/latihan-soal/$id'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AuthenticatedLatihanSoalRiwayatIndexRouteImport } from './routes/_authenticated/latihan-soal/riwayat/index'
import { Route as AuthenticatedDashboardFlashcardIndexRouteImport } from './routes/_authenticated/dashboard/flashcard.index'
import { Route as AuthenticatedClassesShortNameIndexRouteImport } from './routes/_authenticated/classes/$shortName/index'
import { Route as AdminAdminQuestionsIndexRouteImport } from './routes/_admin/admin/questions/index'
import { Route as AdminAdminPracticePacksIndexRouteImport } from './routes/_admin/admin/practice-packs/index'
import { Route as AdminAdminClassesIndexRouteImport } from './routes/_admin/admin/classes/index'
import { Route as AuthenticatedPremiumPaymentUnfinishRouteImport } from './routes/_authenticated/premium/payment/unfinish'
import { Route as AuthenticatedPremiumPaymentFinishRouteImport } from './routes/_authenticated/premium/payment/finish'
import { Route as AuthenticatedPremiumPaymentErrorRouteImport } from './routes/_authenticated/premium/payment/error'
import { Route as AuthenticatedLatihanSoalRiwayatIdRouteImport } from './routes/_authenticated/latihan-soal/riwayat/$id'
import { Route as AuthenticatedDashboardFlashcardResultRouteImport } from './routes/_authenticated/dashboard/flashcard.result'
import { Route as AuthenticatedClassesShortNameContentIdRouteImport } from './routes/_authenticated/classes/$shortName/$contentId'
import { Route as AdminAdminQuestionsIdRouteImport } from './routes/_admin/admin/questions/$id'
import { Route as AdminAdminPracticePacksCreateRouteImport } from './routes/_admin/admin/practice-packs/create'
import { Route as AdminAdminPracticePacksIdRouteImport } from './routes/_admin/admin/practice-packs/$id'
import { Route as AdminAdminClassesShortNameIndexRouteImport } from './routes/_admin/admin/classes/$shortName/index'
import { Route as AuthenticatedClassesShortNameContentIdVideoRouteImport } from './routes/_authenticated/classes/$shortName/$contentId.video'
import { Route as AuthenticatedClassesShortNameContentIdNotesRouteImport } from './routes/_authenticated/classes/$shortName/$contentId.notes'
import { Route as AuthenticatedClassesShortNameContentIdLatihanSoalRouteImport } from './routes/_authenticated/classes/$shortName/$contentId.latihan-soal'
import { Route as AdminAdminClassesShortNameContentIdRouteImport } from './routes/_admin/admin/classes/$shortName/$contentId'
import { Route as AdminAdminClassesShortNameContentIdVideoRouteImport } from './routes/_admin/admin/classes/$shortName/$contentId.video'
import { Route as AdminAdminClassesShortNameContentIdNotesRouteImport } from './routes/_admin/admin/classes/$shortName/$contentId.notes'
import { Route as AdminAdminClassesShortNameContentIdLatihanSoalRouteImport } from './routes/_admin/admin/classes/$shortName/$contentId.latihan-soal'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedLatihanSoalIndexRoute =
  AuthenticatedLatihanSoalIndexRouteImport.update({
    id: '/latihan-soal/',
    path: '/latihan-soal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedLatihanSoalIdRoute =
  AuthenticatedLatihanSoalIdRouteImport.update({
    id: '/latihan-soal/$id',
    path: '/latihan-soal/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedLatihanSoalRiwayatIndexRoute =
  AuthenticatedLatihanSoalRiwayatIndexRouteImport.update({
    id: '/latihan-soal/riwayat/',
    path: '/latihan-soal/riwayat/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFlashcardIndexRoute =
  AuthenticatedDashboardFlashcardIndexRouteImport.update({
    id: '/dashboard/flashcard/',
    path: '/dashboard/flashcard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesShortNameIndexRoute =
  AuthenticatedClassesShortNameIndexRouteImport.update({
    id: '/classes/$shortName/',
    path: '/classes/$shortName/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminQuestionsIndexRoute =
  AdminAdminQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminPracticePacksIndexRoute =
  AdminAdminPracticePacksIndexRouteImport.update({
    id: '/practice-packs/',
    path: '/practice-packs/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminClassesIndexRoute = AdminAdminClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedPremiumPaymentUnfinishRoute =
  AuthenticatedPremiumPaymentUnfinishRouteImport.update({
    id: '/payment/unfinish',
    path: '/payment/unfinish',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumPaymentFinishRoute =
  AuthenticatedPremiumPaymentFinishRouteImport.update({
    id: '/payment/finish',
    path: '/payment/finish',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumPaymentErrorRoute =
  AuthenticatedPremiumPaymentErrorRouteImport.update({
    id: '/payment/error',
    path: '/payment/error',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedLatihanSoalRiwayatIdRoute =
  AuthenticatedLatihanSoalRiwayatIdRouteImport.update({
    id: '/latihan-soal/riwayat/$id',
    path: '/latihan-soal/riwayat/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFlashcardResultRoute =
  AuthenticatedDashboardFlashcardResultRouteImport.update({
    id: '/dashboard/flashcard/result',
    path: '/dashboard/flashcard/result',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesShortNameContentIdRoute =
  AuthenticatedClassesShortNameContentIdRouteImport.update({
    id: '/classes/$shortName/$contentId',
    path: '/classes/$shortName/$contentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminQuestionsIdRoute = AdminAdminQuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPracticePacksCreateRoute =
  AdminAdminPracticePacksCreateRouteImport.update({
    id: '/practice-packs/create',
    path: '/practice-packs/create',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminPracticePacksIdRoute =
  AdminAdminPracticePacksIdRouteImport.update({
    id: '/practice-packs/$id',
    path: '/practice-packs/$id',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminClassesShortNameIndexRoute =
  AdminAdminClassesShortNameIndexRouteImport.update({
    id: '/classes/$shortName/',
    path: '/classes/$shortName/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AuthenticatedClassesShortNameContentIdVideoRoute =
  AuthenticatedClassesShortNameContentIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AuthenticatedClassesShortNameContentIdRoute,
  } as any)
const AuthenticatedClassesShortNameContentIdNotesRoute =
  AuthenticatedClassesShortNameContentIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedClassesShortNameContentIdRoute,
  } as any)
const AuthenticatedClassesShortNameContentIdLatihanSoalRoute =
  AuthenticatedClassesShortNameContentIdLatihanSoalRouteImport.update({
    id: '/latihan-soal',
    path: '/latihan-soal',
    getParentRoute: () => AuthenticatedClassesShortNameContentIdRoute,
  } as any)
const AdminAdminClassesShortNameContentIdRoute =
  AdminAdminClassesShortNameContentIdRouteImport.update({
    id: '/classes/$shortName/$contentId',
    path: '/classes/$shortName/$contentId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminClassesShortNameContentIdVideoRoute =
  AdminAdminClassesShortNameContentIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AdminAdminClassesShortNameContentIdRoute,
  } as any)
const AdminAdminClassesShortNameContentIdNotesRoute =
  AdminAdminClassesShortNameContentIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AdminAdminClassesShortNameContentIdRoute,
  } as any)
const AdminAdminClassesShortNameContentIdLatihanSoalRoute =
  AdminAdminClassesShortNameContentIdLatihanSoalRouteImport.update({
    id: '/latihan-soal',
    path: '/latihan-soal',
    getParentRoute: () => AdminAdminClassesShortNameContentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/latihan-soal/$id': typeof AuthenticatedLatihanSoalIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/latihan-soal': typeof AuthenticatedLatihanSoalIndexRoute
  '/admin/practice-packs/$id': typeof AdminAdminPracticePacksIdRoute
  '/admin/practice-packs/create': typeof AdminAdminPracticePacksCreateRoute
  '/admin/questions/$id': typeof AdminAdminQuestionsIdRoute
  '/classes/$shortName/$contentId': typeof AuthenticatedClassesShortNameContentIdRouteWithChildren
  '/dashboard/flashcard/result': typeof AuthenticatedDashboardFlashcardResultRoute
  '/latihan-soal/riwayat/$id': typeof AuthenticatedLatihanSoalRiwayatIdRoute
  '/premium/payment/error': typeof AuthenticatedPremiumPaymentErrorRoute
  '/premium/payment/finish': typeof AuthenticatedPremiumPaymentFinishRoute
  '/premium/payment/unfinish': typeof AuthenticatedPremiumPaymentUnfinishRoute
  '/admin/classes': typeof AdminAdminClassesIndexRoute
  '/admin/practice-packs': typeof AdminAdminPracticePacksIndexRoute
  '/admin/questions': typeof AdminAdminQuestionsIndexRoute
  '/classes/$shortName': typeof AuthenticatedClassesShortNameIndexRoute
  '/dashboard/flashcard': typeof AuthenticatedDashboardFlashcardIndexRoute
  '/latihan-soal/riwayat': typeof AuthenticatedLatihanSoalRiwayatIndexRoute
  '/admin/classes/$shortName/$contentId': typeof AdminAdminClassesShortNameContentIdRouteWithChildren
  '/classes/$shortName/$contentId/latihan-soal': typeof AuthenticatedClassesShortNameContentIdLatihanSoalRoute
  '/classes/$shortName/$contentId/notes': typeof AuthenticatedClassesShortNameContentIdNotesRoute
  '/classes/$shortName/$contentId/video': typeof AuthenticatedClassesShortNameContentIdVideoRoute
  '/admin/classes/$shortName': typeof AdminAdminClassesShortNameIndexRoute
  '/admin/classes/$shortName/$contentId/latihan-soal': typeof AdminAdminClassesShortNameContentIdLatihanSoalRoute
  '/admin/classes/$shortName/$contentId/notes': typeof AdminAdminClassesShortNameContentIdNotesRoute
  '/admin/classes/$shortName/$contentId/video': typeof AdminAdminClassesShortNameContentIdVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/latihan-soal/$id': typeof AuthenticatedLatihanSoalIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/latihan-soal': typeof AuthenticatedLatihanSoalIndexRoute
  '/admin/practice-packs/$id': typeof AdminAdminPracticePacksIdRoute
  '/admin/practice-packs/create': typeof AdminAdminPracticePacksCreateRoute
  '/admin/questions/$id': typeof AdminAdminQuestionsIdRoute
  '/classes/$shortName/$contentId': typeof AuthenticatedClassesShortNameContentIdRouteWithChildren
  '/dashboard/flashcard/result': typeof AuthenticatedDashboardFlashcardResultRoute
  '/latihan-soal/riwayat/$id': typeof AuthenticatedLatihanSoalRiwayatIdRoute
  '/premium/payment/error': typeof AuthenticatedPremiumPaymentErrorRoute
  '/premium/payment/finish': typeof AuthenticatedPremiumPaymentFinishRoute
  '/premium/payment/unfinish': typeof AuthenticatedPremiumPaymentUnfinishRoute
  '/admin/classes': typeof AdminAdminClassesIndexRoute
  '/admin/practice-packs': typeof AdminAdminPracticePacksIndexRoute
  '/admin/questions': typeof AdminAdminQuestionsIndexRoute
  '/classes/$shortName': typeof AuthenticatedClassesShortNameIndexRoute
  '/dashboard/flashcard': typeof AuthenticatedDashboardFlashcardIndexRoute
  '/latihan-soal/riwayat': typeof AuthenticatedLatihanSoalRiwayatIndexRoute
  '/admin/classes/$shortName/$contentId': typeof AdminAdminClassesShortNameContentIdRouteWithChildren
  '/classes/$shortName/$contentId/latihan-soal': typeof AuthenticatedClassesShortNameContentIdLatihanSoalRoute
  '/classes/$shortName/$contentId/notes': typeof AuthenticatedClassesShortNameContentIdNotesRoute
  '/classes/$shortName/$contentId/video': typeof AuthenticatedClassesShortNameContentIdVideoRoute
  '/admin/classes/$shortName': typeof AdminAdminClassesShortNameIndexRoute
  '/admin/classes/$shortName/$contentId/latihan-soal': typeof AdminAdminClassesShortNameContentIdLatihanSoalRoute
  '/admin/classes/$shortName/$contentId/notes': typeof AdminAdminClassesShortNameContentIdNotesRoute
  '/admin/classes/$shortName/$contentId/video': typeof AdminAdminClassesShortNameContentIdVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_authenticated/latihan-soal/$id': typeof AuthenticatedLatihanSoalIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/latihan-soal/': typeof AuthenticatedLatihanSoalIndexRoute
  '/_admin/admin/practice-packs/$id': typeof AdminAdminPracticePacksIdRoute
  '/_admin/admin/practice-packs/create': typeof AdminAdminPracticePacksCreateRoute
  '/_admin/admin/questions/$id': typeof AdminAdminQuestionsIdRoute
  '/_authenticated/classes/$shortName/$contentId': typeof AuthenticatedClassesShortNameContentIdRouteWithChildren
  '/_authenticated/dashboard/flashcard/result': typeof AuthenticatedDashboardFlashcardResultRoute
  '/_authenticated/latihan-soal/riwayat/$id': typeof AuthenticatedLatihanSoalRiwayatIdRoute
  '/_authenticated/premium/payment/error': typeof AuthenticatedPremiumPaymentErrorRoute
  '/_authenticated/premium/payment/finish': typeof AuthenticatedPremiumPaymentFinishRoute
  '/_authenticated/premium/payment/unfinish': typeof AuthenticatedPremiumPaymentUnfinishRoute
  '/_admin/admin/classes/': typeof AdminAdminClassesIndexRoute
  '/_admin/admin/practice-packs/': typeof AdminAdminPracticePacksIndexRoute
  '/_admin/admin/questions/': typeof AdminAdminQuestionsIndexRoute
  '/_authenticated/classes/$shortName/': typeof AuthenticatedClassesShortNameIndexRoute
  '/_authenticated/dashboard/flashcard/': typeof AuthenticatedDashboardFlashcardIndexRoute
  '/_authenticated/latihan-soal/riwayat/': typeof AuthenticatedLatihanSoalRiwayatIndexRoute
  '/_admin/admin/classes/$shortName/$contentId': typeof AdminAdminClassesShortNameContentIdRouteWithChildren
  '/_authenticated/classes/$shortName/$contentId/latihan-soal': typeof AuthenticatedClassesShortNameContentIdLatihanSoalRoute
  '/_authenticated/classes/$shortName/$contentId/notes': typeof AuthenticatedClassesShortNameContentIdNotesRoute
  '/_authenticated/classes/$shortName/$contentId/video': typeof AuthenticatedClassesShortNameContentIdVideoRoute
  '/_admin/admin/classes/$shortName/': typeof AdminAdminClassesShortNameIndexRoute
  '/_admin/admin/classes/$shortName/$contentId/latihan-soal': typeof AdminAdminClassesShortNameContentIdLatihanSoalRoute
  '/_admin/admin/classes/$shortName/$contentId/notes': typeof AdminAdminClassesShortNameContentIdNotesRoute
  '/_admin/admin/classes/$shortName/$contentId/video': typeof AdminAdminClassesShortNameContentIdVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/premium'
    | '/admin/dashboard'
    | '/latihan-soal/$id'
    | '/admin/'
    | '/classes'
    | '/dashboard'
    | '/latihan-soal'
    | '/admin/practice-packs/$id'
    | '/admin/practice-packs/create'
    | '/admin/questions/$id'
    | '/classes/$shortName/$contentId'
    | '/dashboard/flashcard/result'
    | '/latihan-soal/riwayat/$id'
    | '/premium/payment/error'
    | '/premium/payment/finish'
    | '/premium/payment/unfinish'
    | '/admin/classes'
    | '/admin/practice-packs'
    | '/admin/questions'
    | '/classes/$shortName'
    | '/dashboard/flashcard'
    | '/latihan-soal/riwayat'
    | '/admin/classes/$shortName/$contentId'
    | '/classes/$shortName/$contentId/latihan-soal'
    | '/classes/$shortName/$contentId/notes'
    | '/classes/$shortName/$contentId/video'
    | '/admin/classes/$shortName'
    | '/admin/classes/$shortName/$contentId/latihan-soal'
    | '/admin/classes/$shortName/$contentId/notes'
    | '/admin/classes/$shortName/$contentId/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/premium'
    | '/admin/dashboard'
    | '/latihan-soal/$id'
    | '/admin'
    | '/classes'
    | '/dashboard'
    | '/latihan-soal'
    | '/admin/practice-packs/$id'
    | '/admin/practice-packs/create'
    | '/admin/questions/$id'
    | '/classes/$shortName/$contentId'
    | '/dashboard/flashcard/result'
    | '/latihan-soal/riwayat/$id'
    | '/premium/payment/error'
    | '/premium/payment/finish'
    | '/premium/payment/unfinish'
    | '/admin/classes'
    | '/admin/practice-packs'
    | '/admin/questions'
    | '/classes/$shortName'
    | '/dashboard/flashcard'
    | '/latihan-soal/riwayat'
    | '/admin/classes/$shortName/$contentId'
    | '/classes/$shortName/$contentId/latihan-soal'
    | '/classes/$shortName/$contentId/notes'
    | '/classes/$shortName/$contentId/video'
    | '/admin/classes/$shortName'
    | '/admin/classes/$shortName/$contentId/latihan-soal'
    | '/admin/classes/$shortName/$contentId/notes'
    | '/admin/classes/$shortName/$contentId/video'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_authenticated'
    | '/_admin/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_authenticated/premium'
    | '/_admin/admin/dashboard'
    | '/_authenticated/latihan-soal/$id'
    | '/_admin/admin/'
    | '/_authenticated/classes/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/latihan-soal/'
    | '/_admin/admin/practice-packs/$id'
    | '/_admin/admin/practice-packs/create'
    | '/_admin/admin/questions/$id'
    | '/_authenticated/classes/$shortName/$contentId'
    | '/_authenticated/dashboard/flashcard/result'
    | '/_authenticated/latihan-soal/riwayat/$id'
    | '/_authenticated/premium/payment/error'
    | '/_authenticated/premium/payment/finish'
    | '/_authenticated/premium/payment/unfinish'
    | '/_admin/admin/classes/'
    | '/_admin/admin/practice-packs/'
    | '/_admin/admin/questions/'
    | '/_authenticated/classes/$shortName/'
    | '/_authenticated/dashboard/flashcard/'
    | '/_authenticated/latihan-soal/riwayat/'
    | '/_admin/admin/classes/$shortName/$contentId'
    | '/_authenticated/classes/$shortName/$contentId/latihan-soal'
    | '/_authenticated/classes/$shortName/$contentId/notes'
    | '/_authenticated/classes/$shortName/$contentId/video'
    | '/_admin/admin/classes/$shortName/'
    | '/_admin/admin/classes/$shortName/$contentId/latihan-soal'
    | '/_admin/admin/classes/$shortName/$contentId/notes'
    | '/_admin/admin/classes/$shortName/$contentId/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/latihan-soal/': {
      id: '/_authenticated/latihan-soal/'
      path: '/latihan-soal'
      fullPath: '/latihan-soal'
      preLoaderRoute: typeof AuthenticatedLatihanSoalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/latihan-soal/$id': {
      id: '/_authenticated/latihan-soal/$id'
      path: '/latihan-soal/$id'
      fullPath: '/latihan-soal/$id'
      preLoaderRoute: typeof AuthenticatedLatihanSoalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/latihan-soal/riwayat/': {
      id: '/_authenticated/latihan-soal/riwayat/'
      path: '/latihan-soal/riwayat'
      fullPath: '/latihan-soal/riwayat'
      preLoaderRoute: typeof AuthenticatedLatihanSoalRiwayatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/flashcard/': {
      id: '/_authenticated/dashboard/flashcard/'
      path: '/dashboard/flashcard'
      fullPath: '/dashboard/flashcard'
      preLoaderRoute: typeof AuthenticatedDashboardFlashcardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$shortName/': {
      id: '/_authenticated/classes/$shortName/'
      path: '/classes/$shortName'
      fullPath: '/classes/$shortName'
      preLoaderRoute: typeof AuthenticatedClassesShortNameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/questions/': {
      id: '/_admin/admin/questions/'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminAdminQuestionsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/practice-packs/': {
      id: '/_admin/admin/practice-packs/'
      path: '/practice-packs'
      fullPath: '/admin/practice-packs'
      preLoaderRoute: typeof AdminAdminPracticePacksIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/classes/': {
      id: '/_admin/admin/classes/'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminAdminClassesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/premium/payment/unfinish': {
      id: '/_authenticated/premium/payment/unfinish'
      path: '/payment/unfinish'
      fullPath: '/premium/payment/unfinish'
      preLoaderRoute: typeof AuthenticatedPremiumPaymentUnfinishRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/payment/finish': {
      id: '/_authenticated/premium/payment/finish'
      path: '/payment/finish'
      fullPath: '/premium/payment/finish'
      preLoaderRoute: typeof AuthenticatedPremiumPaymentFinishRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/payment/error': {
      id: '/_authenticated/premium/payment/error'
      path: '/payment/error'
      fullPath: '/premium/payment/error'
      preLoaderRoute: typeof AuthenticatedPremiumPaymentErrorRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/latihan-soal/riwayat/$id': {
      id: '/_authenticated/latihan-soal/riwayat/$id'
      path: '/latihan-soal/riwayat/$id'
      fullPath: '/latihan-soal/riwayat/$id'
      preLoaderRoute: typeof AuthenticatedLatihanSoalRiwayatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/flashcard/result': {
      id: '/_authenticated/dashboard/flashcard/result'
      path: '/dashboard/flashcard/result'
      fullPath: '/dashboard/flashcard/result'
      preLoaderRoute: typeof AuthenticatedDashboardFlashcardResultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$shortName/$contentId': {
      id: '/_authenticated/classes/$shortName/$contentId'
      path: '/classes/$shortName/$contentId'
      fullPath: '/classes/$shortName/$contentId'
      preLoaderRoute: typeof AuthenticatedClassesShortNameContentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/questions/$id': {
      id: '/_admin/admin/questions/$id'
      path: '/questions/$id'
      fullPath: '/admin/questions/$id'
      preLoaderRoute: typeof AdminAdminQuestionsIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/practice-packs/create': {
      id: '/_admin/admin/practice-packs/create'
      path: '/practice-packs/create'
      fullPath: '/admin/practice-packs/create'
      preLoaderRoute: typeof AdminAdminPracticePacksCreateRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/practice-packs/$id': {
      id: '/_admin/admin/practice-packs/$id'
      path: '/practice-packs/$id'
      fullPath: '/admin/practice-packs/$id'
      preLoaderRoute: typeof AdminAdminPracticePacksIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/classes/$shortName/': {
      id: '/_admin/admin/classes/$shortName/'
      path: '/classes/$shortName'
      fullPath: '/admin/classes/$shortName'
      preLoaderRoute: typeof AdminAdminClassesShortNameIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/classes/$shortName/$contentId/video': {
      id: '/_authenticated/classes/$shortName/$contentId/video'
      path: '/video'
      fullPath: '/classes/$shortName/$contentId/video'
      preLoaderRoute: typeof AuthenticatedClassesShortNameContentIdVideoRouteImport
      parentRoute: typeof AuthenticatedClassesShortNameContentIdRoute
    }
    '/_authenticated/classes/$shortName/$contentId/notes': {
      id: '/_authenticated/classes/$shortName/$contentId/notes'
      path: '/notes'
      fullPath: '/classes/$shortName/$contentId/notes'
      preLoaderRoute: typeof AuthenticatedClassesShortNameContentIdNotesRouteImport
      parentRoute: typeof AuthenticatedClassesShortNameContentIdRoute
    }
    '/_authenticated/classes/$shortName/$contentId/latihan-soal': {
      id: '/_authenticated/classes/$shortName/$contentId/latihan-soal'
      path: '/latihan-soal'
      fullPath: '/classes/$shortName/$contentId/latihan-soal'
      preLoaderRoute: typeof AuthenticatedClassesShortNameContentIdLatihanSoalRouteImport
      parentRoute: typeof AuthenticatedClassesShortNameContentIdRoute
    }
    '/_admin/admin/classes/$shortName/$contentId': {
      id: '/_admin/admin/classes/$shortName/$contentId'
      path: '/classes/$shortName/$contentId'
      fullPath: '/admin/classes/$shortName/$contentId'
      preLoaderRoute: typeof AdminAdminClassesShortNameContentIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/classes/$shortName/$contentId/video': {
      id: '/_admin/admin/classes/$shortName/$contentId/video'
      path: '/video'
      fullPath: '/admin/classes/$shortName/$contentId/video'
      preLoaderRoute: typeof AdminAdminClassesShortNameContentIdVideoRouteImport
      parentRoute: typeof AdminAdminClassesShortNameContentIdRoute
    }
    '/_admin/admin/classes/$shortName/$contentId/notes': {
      id: '/_admin/admin/classes/$shortName/$contentId/notes'
      path: '/notes'
      fullPath: '/admin/classes/$shortName/$contentId/notes'
      preLoaderRoute: typeof AdminAdminClassesShortNameContentIdNotesRouteImport
      parentRoute: typeof AdminAdminClassesShortNameContentIdRoute
    }
    '/_admin/admin/classes/$shortName/$contentId/latihan-soal': {
      id: '/_admin/admin/classes/$shortName/$contentId/latihan-soal'
      path: '/latihan-soal'
      fullPath: '/admin/classes/$shortName/$contentId/latihan-soal'
      preLoaderRoute: typeof AdminAdminClassesShortNameContentIdLatihanSoalRouteImport
      parentRoute: typeof AdminAdminClassesShortNameContentIdRoute
    }
  }
}

interface AdminAdminClassesShortNameContentIdRouteChildren {
  AdminAdminClassesShortNameContentIdLatihanSoalRoute: typeof AdminAdminClassesShortNameContentIdLatihanSoalRoute
  AdminAdminClassesShortNameContentIdNotesRoute: typeof AdminAdminClassesShortNameContentIdNotesRoute
  AdminAdminClassesShortNameContentIdVideoRoute: typeof AdminAdminClassesShortNameContentIdVideoRoute
}

const AdminAdminClassesShortNameContentIdRouteChildren: AdminAdminClassesShortNameContentIdRouteChildren =
  {
    AdminAdminClassesShortNameContentIdLatihanSoalRoute:
      AdminAdminClassesShortNameContentIdLatihanSoalRoute,
    AdminAdminClassesShortNameContentIdNotesRoute:
      AdminAdminClassesShortNameContentIdNotesRoute,
    AdminAdminClassesShortNameContentIdVideoRoute:
      AdminAdminClassesShortNameContentIdVideoRoute,
  }

const AdminAdminClassesShortNameContentIdRouteWithChildren =
  AdminAdminClassesShortNameContentIdRoute._addFileChildren(
    AdminAdminClassesShortNameContentIdRouteChildren,
  )

interface AdminAdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminPracticePacksIdRoute: typeof AdminAdminPracticePacksIdRoute
  AdminAdminPracticePacksCreateRoute: typeof AdminAdminPracticePacksCreateRoute
  AdminAdminQuestionsIdRoute: typeof AdminAdminQuestionsIdRoute
  AdminAdminClassesIndexRoute: typeof AdminAdminClassesIndexRoute
  AdminAdminPracticePacksIndexRoute: typeof AdminAdminPracticePacksIndexRoute
  AdminAdminQuestionsIndexRoute: typeof AdminAdminQuestionsIndexRoute
  AdminAdminClassesShortNameContentIdRoute: typeof AdminAdminClassesShortNameContentIdRouteWithChildren
  AdminAdminClassesShortNameIndexRoute: typeof AdminAdminClassesShortNameIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminPracticePacksIdRoute: AdminAdminPracticePacksIdRoute,
  AdminAdminPracticePacksCreateRoute: AdminAdminPracticePacksCreateRoute,
  AdminAdminQuestionsIdRoute: AdminAdminQuestionsIdRoute,
  AdminAdminClassesIndexRoute: AdminAdminClassesIndexRoute,
  AdminAdminPracticePacksIndexRoute: AdminAdminPracticePacksIndexRoute,
  AdminAdminQuestionsIndexRoute: AdminAdminQuestionsIndexRoute,
  AdminAdminClassesShortNameContentIdRoute:
    AdminAdminClassesShortNameContentIdRouteWithChildren,
  AdminAdminClassesShortNameIndexRoute: AdminAdminClassesShortNameIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedPremiumRouteChildren {
  AuthenticatedPremiumPaymentErrorRoute: typeof AuthenticatedPremiumPaymentErrorRoute
  AuthenticatedPremiumPaymentFinishRoute: typeof AuthenticatedPremiumPaymentFinishRoute
  AuthenticatedPremiumPaymentUnfinishRoute: typeof AuthenticatedPremiumPaymentUnfinishRoute
}

const AuthenticatedPremiumRouteChildren: AuthenticatedPremiumRouteChildren = {
  AuthenticatedPremiumPaymentErrorRoute: AuthenticatedPremiumPaymentErrorRoute,
  AuthenticatedPremiumPaymentFinishRoute:
    AuthenticatedPremiumPaymentFinishRoute,
  AuthenticatedPremiumPaymentUnfinishRoute:
    AuthenticatedPremiumPaymentUnfinishRoute,
}

const AuthenticatedPremiumRouteWithChildren =
  AuthenticatedPremiumRoute._addFileChildren(AuthenticatedPremiumRouteChildren)

interface AuthenticatedClassesShortNameContentIdRouteChildren {
  AuthenticatedClassesShortNameContentIdLatihanSoalRoute: typeof AuthenticatedClassesShortNameContentIdLatihanSoalRoute
  AuthenticatedClassesShortNameContentIdNotesRoute: typeof AuthenticatedClassesShortNameContentIdNotesRoute
  AuthenticatedClassesShortNameContentIdVideoRoute: typeof AuthenticatedClassesShortNameContentIdVideoRoute
}

const AuthenticatedClassesShortNameContentIdRouteChildren: AuthenticatedClassesShortNameContentIdRouteChildren =
  {
    AuthenticatedClassesShortNameContentIdLatihanSoalRoute:
      AuthenticatedClassesShortNameContentIdLatihanSoalRoute,
    AuthenticatedClassesShortNameContentIdNotesRoute:
      AuthenticatedClassesShortNameContentIdNotesRoute,
    AuthenticatedClassesShortNameContentIdVideoRoute:
      AuthenticatedClassesShortNameContentIdVideoRoute,
  }

const AuthenticatedClassesShortNameContentIdRouteWithChildren =
  AuthenticatedClassesShortNameContentIdRoute._addFileChildren(
    AuthenticatedClassesShortNameContentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRouteWithChildren
  AuthenticatedLatihanSoalIdRoute: typeof AuthenticatedLatihanSoalIdRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedLatihanSoalIndexRoute: typeof AuthenticatedLatihanSoalIndexRoute
  AuthenticatedClassesShortNameContentIdRoute: typeof AuthenticatedClassesShortNameContentIdRouteWithChildren
  AuthenticatedDashboardFlashcardResultRoute: typeof AuthenticatedDashboardFlashcardResultRoute
  AuthenticatedLatihanSoalRiwayatIdRoute: typeof AuthenticatedLatihanSoalRiwayatIdRoute
  AuthenticatedClassesShortNameIndexRoute: typeof AuthenticatedClassesShortNameIndexRoute
  AuthenticatedDashboardFlashcardIndexRoute: typeof AuthenticatedDashboardFlashcardIndexRoute
  AuthenticatedLatihanSoalRiwayatIndexRoute: typeof AuthenticatedLatihanSoalRiwayatIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPremiumRoute: AuthenticatedPremiumRouteWithChildren,
  AuthenticatedLatihanSoalIdRoute: AuthenticatedLatihanSoalIdRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedLatihanSoalIndexRoute: AuthenticatedLatihanSoalIndexRoute,
  AuthenticatedClassesShortNameContentIdRoute:
    AuthenticatedClassesShortNameContentIdRouteWithChildren,
  AuthenticatedDashboardFlashcardResultRoute:
    AuthenticatedDashboardFlashcardResultRoute,
  AuthenticatedLatihanSoalRiwayatIdRoute:
    AuthenticatedLatihanSoalRiwayatIdRoute,
  AuthenticatedClassesShortNameIndexRoute:
    AuthenticatedClassesShortNameIndexRoute,
  AuthenticatedDashboardFlashcardIndexRoute:
    AuthenticatedDashboardFlashcardIndexRoute,
  AuthenticatedLatihanSoalRiwayatIndexRoute:
    AuthenticatedLatihanSoalRiwayatIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
