/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadRouteImport } from './routes/load'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BeforeLoadRouteImport } from './routes/before-load'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LatihanSoalIndexRouteImport } from './routes/latihan-soal/index'
import { Route as LatihanSoalIdRouteImport } from './routes/latihan-soal/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadRoute = LoadRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeLoadRoute = BeforeLoadRouteImport.update({
  id: '/before-load',
  path: '/before-load',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanSoalIndexRoute = LatihanSoalIndexRouteImport.update({
  id: '/latihan-soal/',
  path: '/latihan-soal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanSoalIdRoute = LatihanSoalIdRouteImport.update({
  id: '/latihan-soal/$id',
  path: '/latihan-soal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/before-load': typeof BeforeLoadRoute
  '/dashboard': typeof DashboardRoute
  '/load': typeof LoadRoute
  '/login': typeof LoginRoute
  '/latihan-soal/$id': typeof LatihanSoalIdRoute
  '/latihan-soal': typeof LatihanSoalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/before-load': typeof BeforeLoadRoute
  '/dashboard': typeof DashboardRoute
  '/load': typeof LoadRoute
  '/login': typeof LoginRoute
  '/latihan-soal/$id': typeof LatihanSoalIdRoute
  '/latihan-soal': typeof LatihanSoalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/before-load': typeof BeforeLoadRoute
  '/dashboard': typeof DashboardRoute
  '/load': typeof LoadRoute
  '/login': typeof LoginRoute
  '/latihan-soal/$id': typeof LatihanSoalIdRoute
  '/latihan-soal/': typeof LatihanSoalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/before-load'
    | '/dashboard'
    | '/load'
    | '/login'
    | '/latihan-soal/$id'
    | '/latihan-soal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/before-load'
    | '/dashboard'
    | '/load'
    | '/login'
    | '/latihan-soal/$id'
    | '/latihan-soal'
  id:
    | '__root__'
    | '/'
    | '/before-load'
    | '/dashboard'
    | '/load'
    | '/login'
    | '/latihan-soal/$id'
    | '/latihan-soal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeforeLoadRoute: typeof BeforeLoadRoute
  DashboardRoute: typeof DashboardRoute
  LoadRoute: typeof LoadRoute
  LoginRoute: typeof LoginRoute
  LatihanSoalIdRoute: typeof LatihanSoalIdRoute
  LatihanSoalIndexRoute: typeof LatihanSoalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load': {
      id: '/load'
      path: '/load'
      fullPath: '/load'
      preLoaderRoute: typeof LoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-load': {
      id: '/before-load'
      path: '/before-load'
      fullPath: '/before-load'
      preLoaderRoute: typeof BeforeLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan-soal/': {
      id: '/latihan-soal/'
      path: '/latihan-soal'
      fullPath: '/latihan-soal'
      preLoaderRoute: typeof LatihanSoalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan-soal/$id': {
      id: '/latihan-soal/$id'
      path: '/latihan-soal/$id'
      fullPath: '/latihan-soal/$id'
      preLoaderRoute: typeof LatihanSoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeforeLoadRoute: BeforeLoadRoute,
  DashboardRoute: DashboardRoute,
  LoadRoute: LoadRoute,
  LoginRoute: LoginRoute,
  LatihanSoalIdRoute: LatihanSoalIdRoute,
  LatihanSoalIndexRoute: LatihanSoalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
